{{- if .Values.postgres.enabled -}}
{{- $component := "postgres" }}
{{- $name := include "ravnar.component-name" (dict "top" . "component" $component) }}
{{- $passwordExplicit := not (empty .Values.postgres.password) }}
{{- $username := "huginn" }}
{{- $password := "" }}
{{- $host := include "ravnar.component-name" (dict "top" . "component" $component) }}
{{- $port := "5432" }}
{{- $database := "ravnar" }}
{{- if not $passwordExplicit }}
  {{- if $existingSecret := lookup "v1" "Secret" .Release.Namespace $name }}
    {{- $password = (index $existingSecret.data "password" | b64dec) }}
  {{- end }}
  {{- if not $password }}
    {{- $password = randAlphaNum 24 }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ravnar.labels" (dict "top" . "component" $component) | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  username: {{ $username }}
{{- if not $passwordExplicit }}
  password: {{ $password }}
{{- end }}
  host: {{ $host }}
  port: {{ $port }}
  database: {{ $database }}
{{- end -}}
