{{- if .Values.postgres.enabled -}}
{{- $component := "postgres" }}
{{- $name := include "ravnar.component-name" (dict "top" . "component" $component) }}
{{- $username := "" }}
{{- $password := "" }}
{{- if $existingSecret := lookup "v1" "Secret" .Release.Namespace $name }}
  {{- $username = (index $existingSecret.data "username" | b64dec) }}
  {{- $password = (index $existingSecret.data "password" | b64dec) }}
{{- else }}
  {{- $username = "huginn" }}
  {{- $password = randAlphaNum 24 }}
{{- end }}
{{- $database := "ravnar" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ravnar.labels" (dict "top" . "component" $component) | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  username: {{ $username }}
  password: {{ $password }}
  database: {{ $database }}
  resource: {{ $name }}:5432/{{ $database }}
{{- end -}}
