name: docker

on:
  pull_request:
    types:
      - closed

env:
  IMAGE: quay.io/nebari/ravnar

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Install Skopeo and jq
        run: |
          sudo apt-get update
          sudo apt-get install --yes skopeo jq

      - name: Login to Quay.io
        run: |
          echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | skopeo login --username "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin quay.io

      - name: Delete PR image tags
        run: |
          PR_NUMBER=${{ github.event.number }}
          TAGS=$(skopeo list-tags docker://${{ env.IMAGE }} | jq --raw-output ".Tags[] | select(. | startswith(\"pr-${PR_NUMBER}-\"))" || true)

          if [[ -z "${TAGS}" ]]; then
            echo "No tags found for PR #${PR_NUMBER}"
            exit 0
          fi

          echo "${TAGS}" | xargs -t -I '{tag}' skopeo delete 'docker://${{ env.IMAGE }}:{tag}'
