name: lint

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit

      - name: Setup lint utilities
        run: uv run pre-commit install-hooks

      - name: Run format checks
        run: uv run pre-commit run --all-files --show-diff-on-failure --color=always

  types:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run type checks
        run: uv run mypy

  helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install mise and setup helm
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          mise_toml: |
            [tools]
            helm = "latest"

      - name: Patch helm chart
        uses: ./.github/actions/patch-helm-chart

      - name: Install chart dependencies
        run: helm dependencies update ./helm/ravnar

      - name: Lint chart
        run: helm lint --strict ./helm/ravnar

      - name: Template chart
        run: helm template --namespace ravnar ravnar ./helm/ravnar
