name: test

on:
  pull_request:
    paths:
      - ".github/**"
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version: ["3.11"]
        include:
          - os: ubuntu-latest
            python-version: "3.12"
          - os: ubuntu-latest
            python-version: "3.13"
          - os: ubuntu-latest
            python-version: "3.14"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run tests
        id: tests
        run: uv run pytest --durations=25
